<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE gimp-help:i18n-phrases [
<!ENTITY % URI "'http://www.gimp.org/docs'">
<!ELEMENT gimp-help:i18n-phrases (i18n-record*)>
<!ATTLIST gimp-help:i18n-phrases
    xmlns:gimp-help CDATA #FIXED "%URI"
    linguas         CDATA #REQUIRED>
<!ELEMENT i18n-record (l10n-phrase*)>
<!ATTLIST i18n-record name CDATA #REQUIRED>
<!ELEMENT l10n-phrase (#PCDATA)>
<!ATTLIST l10n-phrase lang CDATA #REQUIRED>
]>


<gimp-help:i18n-phrases xmlns:gimp-help="http://www.gimp.org/docs"
  linguas="en;cs;de;es;fr;it;ko;nl;no">
  
  <!-- Do not touch the "name" attributes!
       They are used by the stylesheet (stylesheets/authors_docbook.xsl)
       to identify and print the authors with the corresponding role. -->

  <i18n-record name="authors">
    <l10n-phrase lang="en">
      GIMP User Manual Authors and Contributors
    </l10n-phrase>
    <l10n-phrase lang="cs">
      Autoři a přispěvatelé k uživatelské příručce GIMPu
    </l10n-phrase>
    <l10n-phrase lang="de">
      Autoren und Mitwirkende des GIMP-Benutzerhandbuches
    </l10n-phrase>
    <l10n-phrase lang="es">
      Autores y contribuyentes al manual de usuario del GIMP
    </l10n-phrase>
    <l10n-phrase lang="fr">
      Auteurs et contributeurs du Guide de l'utilisateur Gimp
    </l10n-phrase>
    <l10n-phrase lang="it">
      Autori e collaboratori del manuale utente di GIMP
    </l10n-phrase>
    <l10n-phrase lang="ko">
	  김프 사용자 설명서 저자 및 기고자
	</l10n-phrase>
    <l10n-phrase lang="nl">
      Schrijvers en medewerkers aan de GIMP Handleiding
    </l10n-phrase>
    <l10n-phrase lang="no">
      Personane bak GIMP-handboka
    </l10n-phrase>
  </i18n-record>

  <i18n-record name="creators">
    <l10n-phrase lang="en">Content Writers</l10n-phrase>
    <l10n-phrase lang="cs">Autoři obsahu</l10n-phrase>
    <l10n-phrase lang="de">Autoren und Mitwirkende</l10n-phrase>
    <l10n-phrase lang="es">Escritores del contenido</l10n-phrase>
    <l10n-phrase lang="fr">Rédacteurs du contenu</l10n-phrase>
    <l10n-phrase lang="it">Autori</l10n-phrase>
    <l10n-phrase lang="ko">본문 저자</l10n-phrase>
    <l10n-phrase lang="nl">Schrijvers en vertalers</l10n-phrase>
    <l10n-phrase lang="no">Forfattarane</l10n-phrase>
  </i18n-record>

  <i18n-record name="documenters">
    <l10n-phrase lang="en">Proof Reading</l10n-phrase>
    <l10n-phrase lang="cs">Korektury</l10n-phrase>
    <l10n-phrase lang="de">Korrekturleser</l10n-phrase>
    <l10n-phrase lang="fr">Relectures</l10n-phrase>
    <l10n-phrase lang="it">Correzione e revisione</l10n-phrase>
    <l10n-phrase lang="ko">교정</l10n-phrase>
    <l10n-phrase lang="nl">Proef lezers</l10n-phrase>
    <l10n-phrase lang="no">Korrekturlesing</l10n-phrase>
  </i18n-record>

  <i18n-record name="artists">
    <l10n-phrase lang="en">Graphics, Stylesheets</l10n-phrase>
    <l10n-phrase lang="cs">Grafika a styly</l10n-phrase>
    <l10n-phrase lang="de">Grafik, Stylesheets</l10n-phrase>
    <l10n-phrase lang="es">Gráficos, hojas de estilo</l10n-phrase>
    <l10n-phrase lang="fr">Graphismes, Feuilles de Style</l10n-phrase>
    <l10n-phrase lang="it">Grafica e fogli di stile</l10n-phrase>
    <l10n-phrase lang="ko">그래픽스, 스타일쉬트</l10n-phrase>
    <l10n-phrase lang="nl">Afbeeldingen en Stijlbladen</l10n-phrase>
    <l10n-phrase lang="no">Grafikk og stilark</l10n-phrase>
  </i18n-record>

  <i18n-record name="technicans">
    <l10n-phrase lang="en">Build System, Technical Contributions</l10n-phrase>
    <l10n-phrase lang="cs">Technické řešení</l10n-phrase>
    <l10n-phrase lang="de">Technische Unterstützung</l10n-phrase>
    <l10n-phrase lang="es">Contribuciones técnicas</l10n-phrase>
    <l10n-phrase lang="fr">Contributions techniques</l10n-phrase>
    <l10n-phrase lang="it">Contributi tecnici</l10n-phrase>
    <l10n-phrase lang="ko">시스템 구축, 기술 지원</l10n-phrase>
    <l10n-phrase lang="nl">Technische Ondersteuning</l10n-phrase>
    <l10n-phrase lang="no">Teknisk støtte</l10n-phrase>
  </i18n-record>

</gimp-help:i18n-phrases>
